name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
change-template: '- #$NUMBER $TITLE @$AUTHOR'
sort-direction: ascending
categories:
  - title: '🚀 Nuove funzioni'
    labels:
      - 'feature'
      - 'enhancement'

  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'

  - title: '🧰 Manutenzione'
    label:
      - 'dependencies'
      - 'documentation'
      - 'maintenance'

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  [![Downloads di questa release](https://img.shields.io/github/downloads/virtualdj/pun_sensor/v$RESOLVED_VERSION/total.svg)](https://github.com/virtualdj/pun_sensor/releases/v$RESOLVED_VERSION)
  ## Cambiamenti

  $CHANGES

  ## ⭐️ Grazie per il contributo a:
  $CONTRIBUTORS
