#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/../.."

if [[ "$1" =~ prerelease|beta ]]; then
    # Install the latest beta version of Home Assistant
    uv pip install --system --prefix "/home/vscode/.local/" --upgrade --prerelease allow homeassistant
else
    # Install the latest stable version of Home Assistant
    uv pip install --system --prefix "/home/vscode/.local/" --upgrade allow homeassistant
fi

# Show the installed version of Home Assistant
echo -e "The installed Home Assistant version is $(hass --version).\n"