name: "Validate"

on:
  push:
    branches:
      - master
  pull_request_target:
    branches:
      - master
  workflow_dispatch:

jobs:
  validate-ruff:
    name: Validate with ruff
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Check ruff
        uses: astral-sh/ruff-action@v3
        with:
          args: 'format --diff'

  validate-hassfest:
    name: Validate with hassfest
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: "Update manifest.json"
        run: |
          python3 ${{ github.workspace }}/.github/workflows/update_manifest.py

      - name: Hassfest validation
        uses: home-assistant/actions/hassfest@master

  validate-hacs:
    name: Validate with HACS
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: "Update manifest.json"
        run: |
          python3 ${{ github.workspace }}/.github/workflows/update_manifest.py

      - name: HACS Validation
        uses: hacs/action@main
        with:
          category: integration

